<?php

namespace App\Imports;

use App\Product;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;


class ProductsImport implements ToModel
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function model(array $row)
    {
        if($row['1'] == 'BOTANICAL NAME') {
            return;
        }
        $exists = \App\Models\Product::where('id',$row['0'])->first();
        //print_r($exists);
        if ($exists) {
            \App\Models\Product::updateOrCreate(
                ['id' => $row[0]],
                [
                    //'plant_id_number' => uniqid() . rand(0000, 9999),
                    'botanical_name' => $row[2],
                    'common_name' => $row[3],
                    'other_product_service_name' => $row[4],
                    'include_on_website' => $row[5],
                    'status' => $row[6],
                    'date_entered' => $row[7],
                    'best_sellers' => $row[8],
                    'new_for_this_year' => $row[9],
                    'other_product_service' => $row[10],
                    'tags' => $row[11],
                    'purchase_options' => $row[12],
                    'pickup_instructions' => $row[13],
                    'pot_size_a' => $row[14],
                    'inventory_count_a' => $row[15],
                    'low_inventory_count_a' => $row[16],
                    'click_to_inquire_a' => $row[17],
                    'pre_order_a' => $row[18],
                    'contractor_price_a' => $row[19],
                    'retail_sale_price_a' => $row[20],
                    'retail_list_price_a' => $row[21],
                    'pot_size_b' => $row[22],
                    'inventory_count_b' => $row[23],
                    'low_inventory_count_b' => $row[24],
                    'click_to_inquire_b' => $row[25],
                    'pre_order_b' => $row[26],
                    'contractor_price_b' => $row[27],
                    'retail_sale_price_b' => $row[28],
                    'retail_list_price_b' => $row[29],
                    'pot_size_c' => $row[30],
                    'inventory_count_c' => $row[31],
                    'low_inventory_count_c' => $row[32],
                    'click_to_inquire_c' => $row[33],
                    'pre_order_c' => $row[34],
                    'contractor_price_c' => $row[35],
                    'retail_sale_price_c' => $row[36],
                    'retail_list_price_c' => $row[37],
                    'wholesale_supplier_name' => $row[38],
                    'plug_tray_sizes' => $row[39],
                    'raw_cost_range' => $row[40],
                    'purchasing_notes' => $row[41],
                    'year_purchased' => $row[42],
                    'shipping_notes' => $row[43],
                    'image_file' => $row[44],
                    'perennial' => $row[45],
                    'shrub' => $row[46],
                    'vine' => $row[47],
                    'grass_bamboo' => $row[48],
                    'hardy_tropical' => $row[49],
                    'water_plant' => $row[50],
                    'annual' => $row[51],
                    'house_deck_plant' => $row[52],
                    'cactus_succulent' => $row[53],
                    'small_tree' => $row[54],
                    'large_tree' => $row[55],
                    'min_zone' => $row[56],
                    'max_zone' => $row[57],
                    'sunlight' => $row[58],
                    'water_rainfall' => $row[59],
                    'soil_quality' => $row[60],
                    'bloom_season' => $row[61],
                    'flower_color' => $row[62],
                    'berry_fruit_color' => $row[63],
                    'spring_foliage_color' => $row[64],
                    'summer_foliage_color' => $row[65],
                    'fall_foliage_color' => $row[66],
                    'has_evergreen_foliage' => $row[67],
                    'has_winter_interest' => $row[68],
                    'scented_flowers' => $row[69],
                    'drought_tolerance' => $row[70],
                    'wet_feet_tolerance' => $row[71],
                    'humidity_tolerance' => $row[72],
                    'wind_tolerence' => $row[73],
                    'poor_soil_tolerance' => $row[74],
                    'height' => $row[75],
                    'width' => $row[76],
                    'growth_rate' => $row[77],
                    'service_life' => $row[78],
                    'maintenance_requirements' => $row[79],
                    'spreading_potential' => $row[80],
                    'yearly_trimming_tips' => $row[81],
                    'plant_grouping_size' => $row[82],
                    'best_side_of_house' => $row[83],
                    'extreme_planting_locations' => $row[84],
                    'ornamental_features' => $row[85],
                    'special_landscape_uses' => $row[86],
                    'possible_pest_problems' => $row[87],
                    'plant_limitations' => $row[88],
                    'sustainable_garden' => $row[89],
                    'native_plant_garden' => $row[90],
                    'bird_wildlife_garden' => $row[91],
                    'butterfly_bee_garden' => $row[92],
                    'lush_tropical_garden' => $row[93],
                    'dry_shade_garden' => $row[94],
                    'edible_medicinal_garden' => $row[95],
                    'rain_garden' => $row[96],
                    'colorado_rustic_garden' => $row[97],
                    'desert_cactus_rock_garden' => $row[98],
                    'video_link' => $row[99],
                    'description' => $row[100],
                    'how_to_grow_in_kansas' => $row[101],
                    'patent_trademark_names' => $row[102],
                    'plant_assets_and_uses' => 'ti',
                    'plant_picture_in_dynascape_y_n' => $row[103],
                    'year_entered_in_dynascape' => $row[104],
                    'updated_at' => time(),
                ]
            );
            return null;
        }
        else {
            return new \App\Models\Product([
                'plant_id_number' => uniqid() . rand(0000, 9999),
                'botanical_name' => $row[2],
                'common_name' => $row[3],
                'other_product_service_name' => $row[4],
                'include_on_website' => $row[5],
                'status' => $row[6],
                'date_entered' => $row[7],
                'best_sellers' => $row[8],
                'new_for_this_year' => $row[9],
                'other_product_service' => $row[10],
                'tags' => $row[11],
                'purchase_options' => $row[12],
                'pickup_instructions' => $row[13],
                'pot_size_a' => $row[14],
                'inventory_count_a' => $row[15],
                'low_inventory_count_a' => $row[16],
                'click_to_inquire_a' => $row[17],
                'pre_order_a' => $row[18],
                'contractor_price_a' => $row[19],
                'retail_sale_price_a' => $row[20],
                'retail_list_price_a' => $row[21],
                'pot_size_b' => $row[22],
                'inventory_count_b' => $row[23],
                'low_inventory_count_b' => $row[24],
                'click_to_inquire_b' => $row[25],
                'pre_order_b' => $row[26],
                'contractor_price_b' => $row[27],
                'retail_sale_price_b' => $row[28],
                'retail_list_price_b' => $row[29],
                'pot_size_c' => $row[30],
                'inventory_count_c' => $row[31],
                'low_inventory_count_c' => $row[32],
                'click_to_inquire_c' => $row[33],
                'pre_order_c' => $row[34],
                'contractor_price_c' => $row[35],
                'retail_sale_price_c' => $row[36],
                'retail_list_price_c' => $row[37],
                'wholesale_supplier_name' => $row[38],
                'plug_tray_sizes' => $row[39],
                'raw_cost_range' => $row[40],
                'purchasing_notes' => $row[41],
                'year_purchased' => $row[42],
                'shipping_notes' => $row[43],
                'image_file' => $row[44],
                'perennial' => $row[45],
                'shrub' => $row[46],
                'vine' => $row[47],
                'grass_bamboo' => $row[48],
                'hardy_tropical' => $row[49],
                'water_plant' => $row[50],
                'annual' => $row[51],
                'house_deck_plant' => $row[52],
                'cactus_succulent' => $row[53],
                'small_tree' => $row[54],
                'large_tree' => $row[55],
                'min_zone' => $row[56],
                'max_zone' => $row[57],
                'sunlight' => $row[58],
                'water_rainfall' => $row[59],
                'soil_quality' => $row[60],
                'bloom_season' => $row[61],
                'flower_color' => $row[62],
                'berry_fruit_color' => $row[63],
                'spring_foliage_color' => $row[64],
                'summer_foliage_color' => $row[65],
                'fall_foliage_color' => $row[66],
                'has_evergreen_foliage' => $row[67],
                'has_winter_interest' => $row[68],
                'scented_flowers' => $row[69],
                'drought_tolerance' => $row[70],
                'wet_feet_tolerance' => $row[71],
                'humidity_tolerance' => $row[72],
                'wind_tolerence' => $row[73],
                'poor_soil_tolerance' => $row[74],
                'height' => $row[75],
                'width' => $row[76],
                'growth_rate' => $row[77],
                'service_life' => $row[78],
                'maintenance_requirements' => $row[79],
                'spreading_potential' => $row[80],
                'yearly_trimming_tips' => $row[81],
                'plant_grouping_size' => $row[82],
                'best_side_of_house' => $row[83],
                'extreme_planting_locations' => $row[84],
                'ornamental_features' => $row[85],
                'special_landscape_uses' => $row[86],
                'possible_pest_problems' => $row[87],
                'plant_limitations' => $row[88],
                'sustainable_garden' => $row[89],
                'native_plant_garden' => $row[90],
                'bird_wildlife_garden' => $row[91],
                'butterfly_bee_garden' => $row[92],
                'lush_tropical_garden' => $row[93],
                'dry_shade_garden' => $row[94],
                'edible_medicinal_garden' => $row[95],
                'rain_garden' => $row[96],
                'colorado_rustic_garden' => $row[97],
                'desert_cactus_rock_garden' => $row[98],
                'video_link' => $row[99],
                'description' => $row[100],
                'how_to_grow_in_kansas' => $row[101],
                'patent_trademark_names' => $row[102],
                'plant_assets_and_uses' => 'ti',
                'plant_picture_in_dynascape_y_n' => $row[103],
                'year_entered_in_dynascape' => $row[104],
                'created_at' => time(),
                'updated_at' => time(),
            ]);
        }
    }
}
